/**
 * Tide Anchor TypeScript integration tests.
 *
 * These run via `anchor test`, which spins up a local
 * solana-test-validator and exercises the program in isolation. They
 * complement the devnet-based scripts in scripts/test-*.mjs that
 * validate the real deployed program. See tests/README.md for the
 * full testing strategy.
 *
 * Each test case in this file maps to an audit-finding closure from
 * the internal review on 2026-05-11. The mapping is also documented
 * in tests/README.md. Running this suite locally provides isolated
 * verification of the same fixes that the devnet pinned-tx scripts
 * verify against shared state.
 *
 * Windows users: `anchor test` requires `solana-test-validator` which
 * runs on Linux/Mac only. From Windows, use WSL2 OR run the devnet
 * integration scripts (`npm run test:refund-flow`, etc) instead.
 */

import * as anchor from "@coral-xyz/anchor";
import { BN, type Program } from "@coral-xyz/anchor";
import {
  Keypair,
  LAMPORTS_PER_SOL,
  PublicKey,
  SystemProgram,
  SYSVAR_RENT_PUBKEY,
} from "@solana/web3.js";
import {
  ASSOCIATED_TOKEN_PROGRAM_ID,
  TOKEN_PROGRAM_ID,
  createMint,
  getOrCreateAssociatedTokenAccount,
  mintTo,
} from "@solana/spl-token";
import { strict as assert } from "node:assert";

// The Tide IDL type is generated by `anchor build`. Tests are written
// against the typed Program but the import is conditional so the file
// compiles even when target/ is empty (e.g. fresh clone).
// eslint-disable-next-line @typescript-eslint/no-explicit-any
type Tide = any;

const SEED_POOL = Buffer.from("pool");
const SEED_DCA = Buffer.from("dca-position");
const SEED_WINDOW = Buffer.from("window");
const SEED_INTENT = Buffer.from("intent");
const SEED_ESCROW = Buffer.from("escrow");

describe("tide — audit-finding closure tests", () => {
  const provider = anchor.AnchorProvider.env();
  anchor.setProvider(provider);

  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  const program = anchor.workspace.Tide as Program<Tide>;

  const admin = Keypair.generate();
  const alice = Keypair.generate();
  const bob = Keypair.generate();

  let usdcMint: PublicKey;
  let targetMint: PublicKey;
  let poolPda: PublicKey;

  function findPoolPda(input: PublicKey, target: PublicKey): PublicKey {
    return PublicKey.findProgramAddressSync(
      [SEED_POOL, input.toBuffer(), target.toBuffer()],
      program.programId,
    )[0];
  }

  function findWindowPda(pool: PublicKey, counter: bigint): PublicKey {
    const counterBuf = Buffer.alloc(8);
    counterBuf.writeBigUInt64LE(counter);
    return PublicKey.findProgramAddressSync(
      [SEED_WINDOW, pool.toBuffer(), counterBuf],
      program.programId,
    )[0];
  }

  before(async () => {
    // Airdrop SOL to test wallets
    for (const kp of [admin, alice, bob]) {
      const sig = await provider.connection.requestAirdrop(
        kp.publicKey,
        2 * LAMPORTS_PER_SOL,
      );
      await provider.connection.confirmTransaction(sig);
    }

    // Create USDC + target mints under admin authority
    usdcMint = await createMint(
      provider.connection,
      admin,
      admin.publicKey,
      null,
      6,
    );
    targetMint = await createMint(
      provider.connection,
      admin,
      admin.publicKey,
      null,
      9, // SOL-like decimals
    );

    poolPda = findPoolPda(usdcMint, targetMint);
  });

  // ── Audit fix #3 (upgrade #3): init_pool min_pool_size > 0 ────────────────
  describe("init_pool — min_pool_size > 0 constraint", () => {
    it("rejects min_pool_size = 0", async () => {
      try {
        await program.methods
          .initPool(targetMint, new BN(900), new BN(0), 5)
          .accountsPartial({
            authority: admin.publicKey,
            inputMint: usdcMint,
            pool: findPoolPda(usdcMint, targetMint),
            systemProgram: SystemProgram.programId,
          })
          .signers([admin])
          .rpc();
        assert.fail("init_pool with min=0 should have reverted");
      } catch (err) {
        // Expect InvalidAmount error code
        const msg = (err as Error).message;
        assert.match(
          msg,
          /InvalidAmount|min_pool_size/i,
          `expected InvalidAmount error, got: ${msg.slice(0, 200)}`,
        );
      }
    });

    it("accepts min_pool_size > 0", async () => {
      const sig = await program.methods
        .initPool(targetMint, new BN(900), new BN(5_000_000), 5)
        .accountsPartial({
          authority: admin.publicKey,
          inputMint: usdcMint,
          pool: poolPda,
          systemProgram: SystemProgram.programId,
        })
        .signers([admin])
        .rpc();
      assert.strictEqual(typeof sig, "string");
    });
  });

  // ── Audit fix #6 (upgrade #6): init_window lifecycle guard ────────────────
  describe("init_window — lifecycle guard", () => {
    it("first window (counter=0) succeeds with poolPda as sentinel", async () => {
      const windowPda = findWindowPda(poolPda, 0n);
      const sig = await program.methods
        .initWindow()
        .accountsPartial({
          caller: alice.publicKey,
          pool: poolPda,
          window: windowPda,
          previousWindow: poolPda, // sentinel for first window
          systemProgram: SystemProgram.programId,
        })
        .signers([alice])
        .rpc();
      assert.strictEqual(typeof sig, "string");
    });

    it("second window rejects when previous is still Open (status=0)", async () => {
      const windowPda = findWindowPda(poolPda, 1n);
      const prevWindow = findWindowPda(poolPda, 0n);
      try {
        await program.methods
          .initWindow()
          .accountsPartial({
            caller: bob.publicKey,
            pool: poolPda,
            window: windowPda,
            previousWindow: prevWindow,
            systemProgram: SystemProgram.programId,
          })
          .signers([bob])
          .rpc();
        assert.fail("init_window with prev.status=Open should have reverted");
      } catch (err) {
        const msg = (err as Error).message;
        assert.match(
          msg,
          /AggregateNotReady/,
          `expected AggregateNotReady, got: ${msg.slice(0, 200)}`,
        );
      }
    });

    // NOTE: full lifecycle (mark_window_failed → init_window succeeds) is
    // validated end-to-end on devnet via scripts/test-refund-flow.mjs +
    // scripts/test-fail-window.mjs. See tests/README.md for the cross-
    // reference.
  });

  // ── Audit fix #1 (upgrade #1+2): commit_intent amount + input_mint bounds ─
  // These cases need the full window lifecycle wired (setup_dca_position
  // + init_window + position bump). The devnet equivalents are validated
  // via scripts/test-refund-flow.mjs which exercises commit_intent under
  // the actual constraints. Skipped in local mocha to avoid stubbing the
  // lifecycle plumbing here — see tests/README.md for the mapping.
  describe("commit_intent — audit constraints", () => {
    it.skip("amount <= position.amount_per_window enforced (devnet-tested)", () => undefined);
    it.skip("input_mint == pool.input_mint enforced (devnet-tested)", () => undefined);
  });

  // ── Audit fix #4 + #5: refund_intent + close_intent ─────────────────────
  // Validated end-to-end on devnet via scripts/test-refund-flow.mjs +
  // scripts/test-close-intent.mjs. Local mocha equivalents need the full
  // setup_dca_position → init_window → commit_intent → trigger_aggregate
  // → mark_window_failed chain stubbed; that's roughly 200 lines of
  // ceremony to reproduce what the devnet scripts already prove against
  // the real deployed bytecode. Left as skipped scaffolds with
  // documented intent.
  describe("mark_window_failed → refund_intent → close_intent flow", () => {
    it.skip("refund_intent rejects window in non-Failed status (devnet-tested)", () => undefined);
    it.skip("close_intent rejects unsettled intent (devnet-tested)", () => undefined);
  });
});
